server:
  port: 8080

spring:
  application:
    name: dream-case-api
  datasource:
    url: jdbc:postgresql://localhost:5432/dreamcaseappdb?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
